'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :4.0.30319.42000
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    'à l'aide d'un outil, tel que ResGen ou Visual Studio.
    'Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    'avec l'option /str ou régénérez votre projet VS.
    '''<summary>
    '''  Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("HyperVoicing.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Remplace la propriété CurrentUICulture du thread actuel pour toutes
        '''  les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _03_splash() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_03_splash", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _32x32_Transp_vert__échelle3_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_32x32_Transp_vert__échelle3_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _48x43_Transp_vert__échelle3_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_48x43_Transp_vert__échelle3_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _48x48_Transp_vert__échelle3_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_48x48_Transp_vert__échelle3_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _49229() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_49229", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property a_propos_v2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("a_propos_v2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Accords16x16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Accords16x16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Appli9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Appli9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ARW06LT() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ARW06LT", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ARW06LTbis() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ARW06LTbis", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ARW06LTbisVerte() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ARW06LTbisVerte", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Base_Binaire() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Base_Binaire", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Base_Ternaire() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Base_Ternaire", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Capture() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Capture", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Clavier() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Clavier", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property COPY_png() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("COPY_png", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Culture2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Culture2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CUT_png() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CUT_png", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DELETE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DELETE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DELETE_png() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DELETE_png", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property domain__1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("domain__1_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DRAWING() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DRAWING", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property emoticon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("emoticon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property exportHTML() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("exportHTML", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property exportHTML2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("exportHTML2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property exportHTML3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("exportHTML3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Maj;3;1;3;5
        '''m;3;1;b3;5
        '''mb5;3;1;b3;b5
        '''M7;4;1;3;5;7
        '''7;4;1;3;5;b7
        '''m7;4;1;b3;5;b7
        '''m7b5;4;1;b3;b5;b7
        '''5#;3;1;3;#5
        '''mM7;4;1;b3;5;7
        '''M75#;4;1;3;#5;7
        '''7dim;4;1;b3;b5;6
        '''7Dim;4;1;b3;b5;6
        '''M7(9);5;1;3;5;7;9
        '''m7(9);5;1;b3;5;b7;9
        '''7(9);5;1;3;5;b7;9
        '''7(b9);5;1;3;5;b7;b9
        '''7(9#);5;1;3;5;b7;#9
        '''b9;4;1;3;5;b9
        '''9#;4;1;3;5;#9
        '''m9;4;1;b3;5;9
        '''9;4;1;3;5;9
        '''M7(11#);5;1;3;5;7;#11
        '''7(11);5;1;3;5;b7;11
        '''11#;4;1;3;5;#11
        '''11;4;1;3;5;11
        '''7sus4;4;1;4;5;b7
        '''sus4;3;1;4;5
        '''m11;4;1;b3;5;11
        '''m7(11);5;1;b3;5;7;11
        '''7M;4;1;3;5;7
        '''m7M;4;1 [le reste de la chaîne a été tronqué]&quot;;.
        '''</summary>
        Friend ReadOnly Property FichierListeAccords() As String
            Get
                Return ResourceManager.GetString("FichierListeAccords", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Usuelle;UsualScale;Maj;1;2;3;4;5;6;7;Fin;
        '''Usuelle;UsualScale;MinH;1;2;b3;4;5;b6;7;Fin;
        '''Usuelle;UsualScale;MinM;1;2;b3;4;5;6;7;Fin;
        '''Usuelle;UsualScale;PMin;1;b3;4;5;b7;Fin;
        '''Pentatoniques Bhupkali;5 notes;PMaj1;1;2;3;5;b6;Fin;
        '''Pentatoniques Penta3;5 notes;PMaj2;1;3;5;6;7;Fin;
        '''Pentatoniques;5 notes;PMin1;1;b3;4;5;b7;Fin;
        '''Pentatoniques Bhupalam;5 notes;PMin2;1;b2;b3;5;b6;Fin;
        '''Pentatoniques;5 notes;PMin3;1;b3;5;b6;b7;Fin;
        '''Pentatoniques Japanese;5 notes;PMin4;1;2;b3;5;b6;Fin;
        '''Pentatoniques Akebono;5 not [le reste de la chaîne a été tronqué]&quot;;.
        '''</summary>
        Friend ReadOnly Property FichierListeGammes() As String
            Get
                Return ResourceManager.GetString("FichierListeGammes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Usuelle;UsualScale;Maj;1;2;3;4;5;6;7;Fin;
        '''Usuelle;UsualScale;MinH;1;2;b3;4;5;b6;7;Fin;
        '''Usuelle;UsualScale;MinM;1;2;b3;4;5;6;7;Fin;
        '''Pentatonique ;UsualScale;Penta;1;2;3;5;6;Fin;
        '''Pentatonique Bhupkali;5 notes;PentaMaj1;1;2;3;5;b6;Fin;
        '''Pentatonique Penta3;5 notes;PentaMaj2;1;3;5;6;7;Fin;
        '''Pentatonique Bhupalam;5 notes;PentaMin1;1;b2;b3;5;b6;Fin;
        '''Pentatonique;5 notes;PentaMin2;1;b3;5;b6;b7;Fin;   
        '''Pentatonique Abhogi;5 notes;PentaMin3;1;2;b3;4;6;Fin;
        '''Blues;8notes;Blues1;1;2;b3;4;#4;5;6;b7;Fin;
        '''Blues;7n [le reste de la chaîne a été tronqué]&quot;;.
        '''</summary>
        Friend ReadOnly Property FichierListeGammes_Cubasev2() As String
            Get
                Return ResourceManager.GetString("FichierListeGammes_Cubasev2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Usuelle;UsualScale;Maj;1;2;3;4;5;6;7;Fin;
        '''MinH;UsualScale;MinH;1;2;b3;4;5;b6;7;Fin;
        '''MinH;UsualScale;Locrien B13;1;b2;b3;4;#4;b6;b7;Fin;
        '''MinH;UsualScale;Ionien 5#;1;2;3;4;#5;6;7;Fin;
        '''MinH;UsualScale;Dorien 11#;1;2;b3;b5;5;6;b7;Fin;
        '''MinH;UsualScale;Mixolydien b9b13;1;2;3;4;5;b6;b7;Fin;
        '''MinH;UsualScale;Lydien 9#;1;b3;3;b5;5;6;7;Fin;
        '''MinH;UsualScale;Altéré bb7;1;b2;b3;3;b5;b6;6;Fin;
        '''MinM;UsualScale;MinM;1;2;b3;4;5;6;7;Fin;
        '''MinM;UsualScale;Dorien b9;1;b2;b3;4;5;6;b7;Fin;
        '''MinM;UsualScale;Lydien 5#;1;2;3 [le reste de la chaîne a été tronqué]&quot;;.
        '''</summary>
        Friend ReadOnly Property FichierListeGammes_Cubasev4() As String
            Get
                Return ResourceManager.GetString("FichierListeGammes_Cubasev4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property flèche_bas_v2_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("flèche_bas_v2.", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fleche_Bleu_vers_droite() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fleche-Bleu vers droite", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fleche_gauche_Bleu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fleche_gauche_Bleu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fleche_gauche_Orange_copie() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fleche_gauche_Orange_copie", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fleche_gauche_Rouge_copie() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fleche_gauche_Rouge_copie", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fleche_gauche_verte() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fleche_gauche_verte", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FR_Manuel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR_Manuel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property globe_earth() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("globe_earth", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property globe_earth24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("globe_earth24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property globe_earth32x32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("globe_earth32x32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Gomme_png() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Gomme_png", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HELP2_png() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HELP2_png", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IconeJouerGamme() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IconeJouerGamme", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IconeJouerGammeDescendre() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IconeJouerGammeDescendre", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IconeJouerGammeInversecopie() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IconeJouerGammeInversecopie", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IconeJouerGammeMonter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IconeJouerGammeMonter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons_2188729_1920_ICON2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons_2188729_1920_ICON2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Interrog() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Interrog", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property language_32x32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("language_32x32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property loupeMoins() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("loupeMoins", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property loupePlus() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("loupePlus", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Marqueurs6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Marqueurs6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MISC31() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MISC31", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NEW_png() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NEW_png", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NOTE6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NOTE6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NOTEBOOK() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NOTEBOOK", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Notes() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Notes", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property OPEN_png() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OPEN_png", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PASTE_png() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PASTE_png", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PLAN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PLAN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Play() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Play", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Play_Inverse22px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Play_Inverse22px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Play_Inverse22Vertpx() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Play_Inverse22Vertpx", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Play1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Play1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Play11_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Play11_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Play22px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Play22px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Play22pxVert() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Play22pxVert", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PRINT() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PRINT", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PRINT1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PRINT1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PRINT55() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PRINT55", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ReinitGraph() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ReinitGraph", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SAVEpng1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SAVEpng1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sourire() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sourire", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property splashnew() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("splashnew", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property star_gif() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("star_gif", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Start24bis() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Start24bis", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property stop_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stop_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Stop11_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Stop11_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Stop24bis() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Stop24bis", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TIMER01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TIMER01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property UNDO_png() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("UNDO_png", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property UNGROUP_png1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("UNGROUP_png1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property us() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("us", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property VersLocators() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VersLocators", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property VWDTLS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VWDTLS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WRENCH() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WRENCH", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
